version: "3.9"
services:
  web:
    build: ./src/frontend
    image: testacrdemo.azurecr.io/frontend:0.1
    ports:
      - "8888:3000"
    environment:
      - MoviesApiUri=http://movies-api
      - RecommendationApiUri=http://recommendation-api
      - BasketApiUri=http://basket-api
    depends_on:
      - movies-api
      - recommendation-api
      - basket-api
  movies-api:
    build: ./src/movies-api
    image: testacrdemo.azurecr.io/movies-api:0.1
    ports:
      - "8088:80"
  recommendation-api:
    build: ./src/recommendation-api
    image: testacrdemo.azurecr.io/recommendation-api:0.2
    ports:
      - "5000:80"
    environment:
      - MOVIE_API_URL=http://movies-api
  ads-api:
    build: ./src/ad-api
    image: testacrdemo.azurecr.io/ad-api:0.1
    ports:
      - "5001:80"
  basket-api:
    build: ./src/basket-api
    image: testacrdemo.azurecr.io/basket-api:0.1
    depends_on:
      - redis
    ports:
      - "9999:9999"
    environment:
      - REDIS_URL=redis:6379
      - DEFAULT_PORT=9999
  checkout-api:
    build: ./src/checkout-api
    image: testacrdemo.azurecr.io/checkout-api:0.1
    depends_on:
      - redis
    ports:
      - "5002:80"
    environment:
      - REDIS_URL=redis
      - NATS_URL=nats://nats:4222
      - NATS_SUBJECT=ORDERS
  locust-leader:
    image: locustio/locust
    scale: 0 #Change to 1 to run load tests
    depends_on:
      - web
    ports:
      - "8089:8089"
    volumes:
      - ./src/load-generator:/mnt/locust
    command: -f /mnt/locust/loadtest.py --master -H http://web:3000 --headless -u 100 -r 10
  locust-worker:
    image: locustio/locust
    volumes:
      - ./src/load-generator:/mnt/locust
    command: -f /mnt/locust/loadtest.py --worker --master-host locust-leader
  redis:
    image: redis
    ports:
      - "6379:6379"
  nats:
    image: nats-streaming
    ports:
      - "4222:4222"
  order-processor:
    build: ./src/order-processor
    image: testacrdemo.azurecr.io/order-processor:0.1
    depends_on:
      - nats
      - db
    environment:
      - NATS_URL=nats://nats:4222
      - NATS_SUBJECT=ORDERS
      - NATS_COMPLETE_SUBJECT=ORDER_PROCESSED
  db:
    image: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kubeflix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
