version: "3.9"
services:
  web:
    build: ./src/frontend
    ports:
      - "8888:3000"
    environment:
      - MoviesApiUri=http://movies-api
      - RecommendationApiUri=http://recommendation-api:5000
    depends_on:
      - movies-api
      - recommendation-api
  movies-api:
    build: ./src/movies-api
    ports:
      - "8088:80"
  recommendation-api:
    build: ./src/recommendation-api
    ports:
      - "5000:5000"
    environment:
      - MOVIE_API_URL=http://movies-api
  locust-leader:
    image: locustio/locust
    scale: 0 #Change to 1 to run load tests
    depends_on: 
      - web
    ports:
      - "8089:8089"
    volumes:
      - ./src/load-generator:/mnt/locust
    command: -f /mnt/locust/loadtest.py --master -H http://web:3000 --headless -u 100 -r 10
  locust-worker:
    image: locustio/locust
    volumes:
      - ./src/load-generator:/mnt/locust
    command: -f /mnt/locust/loadtest.py --worker --master-host locust-leader