apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontend"
        dapr.io/app-port: "3000"
        dapr.io/config: "daprconfig"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: api
        image: hjgraca/frontend:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MoviesApiUri
          value: "http://localhost:3500/v1.0/invoke/movies-api/method"
        - name: RecommendationApiUri
          value: "http://localhost:3500/v1.0/invoke/recommendation-api/method"
        - name: BasketApiUri
          value: "http://localhost:3500/v1.0/invoke/basket-api/method"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          httpGet:
            path: /healthx
            port: 3000
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          httpGet:
            path: /healthz
            port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000