apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-api
  template:
    metadata:
      labels:
        app: recommendation-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "recommendation-api"
        dapr.io/app-port: "5000"
        dapr.io/config: "daprconfig"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: api
        image: hjgraca/recommendation-api:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MOVIE_API_URL
          value: "http://localhost:3500/v1.0/invoke/movies-api/method"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          httpGet:
            path: /healthx
            port: 5000
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          httpGet:
            path: /healthz
            port: 5000